In [1]:
import numpy as np

Loading numpy
Loaded numpy


In [2]:


a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Shape:", a.shape)
print("Mean:", a.mean())
print("Transpose:")
print(a.T)

print("Matrix multiplication:")
print(a @ a)

print("Eigenvalues:")
print(np.linalg.eigvals(a))

Shape: (3, 3)
Mean: 5.0
Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Matrix multiplication:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Eigenvalues:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
